nodeLinker: node-modules

packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": ^7.16.0
      "@babel/plugin-transform-modules-commonjs": ^7.16.0

yarnPath: .yarn/releases/yarn-3.6.1.cjs
